$font = Noto Sans
$clockFont = Adwaita Sans, Extrabold
$dateFont = Adwaita Sans, Regular Italic
$color_mantle = rgb(24, 24, 37)
$color_text = rgb(205, 214, 244)
$color_outer = rgba(0,0,0,0.75)
$color_blue = rgb(137, 180, 250)

background {
    monitor =
    path = /home/jamoy/.cache/current_wallpaper
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
    brightness = 0.45
}

auth {
  fingerprint {
      enabled = true
      ready_message = Scan fingerprint to unlock
      present_message = Scanning...
      retry_delay = 250 # in milliseconds
  }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# GREETING LABEL
label {
  monitor =
  text = cmd[update:999999] echo "<i>$(/home/jamoy/Documents/scripts/welcome-prefix.sh)</i>"
  font_size = 16 
  font_family = $font 
  color = rgba(150, 150, 150, 1.0)
  position = 0, 50
  halign = center
  valign = center
}

# TIME LABEL
label {
  monitor =
  text = cmd[update:1000] date +"%-I:%M %p"
  font_size = 72 
  font_family = $clockFont
  color = $color_blue
  position = 0, 140 
  halign = center
  valign = center
}

# DAY LABEL
label {
  monitor =
  text = cmd[update:999999] date +"%A, %B %d, %Y"
  font_size = 16
  font_family = $dateFont
  color = rgba(150, 150, 150, 1.0)
  position = 0, 80 
  halign = center
  valign = center
}

# PASSWORD INPUT
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $color_outer

    outer_color = $color_outer
    # outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    # check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = $color_text
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}
